### PR TITLE
delete repeated code

### PR DESCRIPTION
**Pull request by cesardariogarcia**

### CODE REVIEW

**Comment by echavezNS** [comment]
LGTM, what do you think @ar-vargas ? I think you did this part.

**Comment by ar-vargas** [comment]
I'm not sure if I forgot delete this code or if this was ignored when merge conflicts were resolve. 
However I think that should works.

**Comment by cesardariogarcia** [comment]
Carlos and I tested the functionality of the function after deleted this piece of code and indeed, was code repeated and it works fine after deleted.

**Comment by cesardariogarcia** [comment]
travis knows! ; ) 8- )

**Pull request merged**
